---
title: "bayesian_regression"
output: html_document
---

```{r}
library(HDInterval)
library(rstan)
library(bayesplot)
```

```{r}
dataPath <- "/Users/chrisolen/Documents/uchicago_courses/optimization/project/urban-demand-allocation/demand_models"
dat<-read.csv(paste(dataPath,"test.csv",sep="/"))
head(dat)
```

```{r}
x <- as.matrix(dat[,c(-1,-2,-3)])
y <- dat[,1]
Ntotal <- dim(x)[1]
Nx <- dim(x)[2]
dataListRegression <- list(Ntotal=Ntotal,
                           y=y,
                           x=x,
                           Nx=Nx)
```

```{r}
modelString <- "
data { 
    int<lower=1> Ntotal; 
    int<lower=1> Nx; 
    vector[Ntotal] y; 
    matrix[Ntotal, Nx] x; 
}
transformed data { 
    real meanY;
    real sdY;
    vector[Ntotal] zy; 
    vector[Nx] meanX;
    vector[Nx] sdX;
    matrix[Ntotal, Nx] zx; 
    meanY = mean(y);
    sdY = sd(y);
    zy = (y - meanY) / sdY;
    for ( j in 1:Nx ) {
        meanX[j] = mean(x[,j]);
        sdX[j] = sd(x[,j]);
        for ( i in 1:Ntotal ) {
            zx[i,j] = ( x[i,j] - meanX[j] ) / sdX[j];
        }
    }
}
parameters {
    real zbeta0;
    vector[Nx] zbeta;
    real<lower=0> sigmaBeta0;
    vector<lower=0>[Nx] sigmaBeta;
    real<lower=0> zsigma;
    real<lower=0> tau;
    real<lower=0> nu;
}
model {
    sigmaBeta0 ~ gamma(3.0, 2.0); // mode=(kappa-1)/theta, var=kappa/theta^2
    zbeta0 ~ student_t(1.0/30.0,0,sigmaBeta0); 
    sigmaBeta ~ gamma(3.0, 2.0); // mode=(kappa-1)/theta, var=kappa/theta^2
    zbeta ~ student_t(1.0/30.0,0,sigmaBeta);
    zsigma ~ gamma(3,1);
    nu ~ gamma(3.0, 2.0);
    tau ~ gamma(nu/2.0,nu/2.0);
    zy ~ normal(zbeta0 + zx * zbeta, 1/sqrt(tau)); 
}
generated quantities { 
    real beta0; 
    vector[Nx] beta;
    beta = sdY * ( zbeta ./ sdX );
    beta0 = zbeta0 * sdY  + meanY - sdY * sum( zbeta .* meanX ./ sdX );
} "
```


```{r}
RobustMultipleRegressionDso <- stan_model( model_code=modelString )
```

```{r}
fit  <- sampling(RobustMultipleRegressionDso,
               data=dataListRegression,
               pars=c('beta0', 'beta','zbeta0','zbeta','sigmaBeta0','sigmaBeta','zsigma', 'nu', 'tau'),
               iter=25000, chains = 8, cores = 4,
               control = list(adapt_delta = .80, max_treedepth = 20))

```

```{r}
demand_features <- colnames(dat[,4:7])
demand_coefs <- c(median(as.matrix(fit)[,2]),
median(as.matrix(fit)[,3]),
median(as.matrix(fit)[,4]),
median(as.matrix(fit)[,5]))
results <- cbind(demand_features, demand_coefs)
write.csv(results, "test.csv", row.names = FALSE)
```
mean(as.matrix(fit)[,1])



```{r}
posterior <- as.array(fit)
lp <- log_posterior(fit)
np <- nuts_params(fit)
rhats <- rhat(fit)
ratios <- neff_ratio(fit)
params <- colnames(as.matrix(fit))
feature_names <- colnames(x)
plot(fit,pars=c("beta"))
hdi(as.matrix(fit)[,3])
hdi(as.matrix(fit)[,5])

```





```{r}
stan_dens(fit)
stan_ac(fit)
mcmc_neff(ratios, size = 2)
color_scheme_set("mix-brightblue-gray") # see help("color_scheme_set")
mcmc_trace(posterior, np = np) + 
  xlab("Post-warmup iteration")
color_scheme_set("brightblue") 
mcmc_rhat(rhats)
color_scheme_set("red")
mcmc_nuts_energy(np)
```


```{r}
### optional model diagnostics ###
color_scheme_set("darkgray")
mcmc_pairs(posterior, np = np, 
           off_diag_args = list(size = 0.75))
mcmc_parcoord(posterior, np = np)
mcmc_scatter(posterior, 
  pars = params[c(2,4)],
  np = np, 
  size = 1)

```

```{r}
#shinystan(fit)
saveRDS(fit, "fit.rds")
```








